########################
# SPRING Configuration #
########################
spring:
  application:
    name: ordering
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ordering;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

### Security ###
security:
  # OAuth2
  oauth2:
    # Common
    issuer-uri: http://localhost:8888/auth/realms/acntech
    authorization-server-uri: ${issuer-uri}/protocol/openid-connect
    # OAuth2 Client
    client:
      client-id: ordering
      client-secret: 22edc96b-523d-4e9b-a15a-0293447a946c
      user-authorization-uri: ${authorization-server-uri}/auth
      access-token-uri: ${authorization-server-uri}/token
      scope:
        - read
        - write
        - openid
      grant-type: client_credentials
    # OAuth2 Resource Server
    resource:
      id: ordering
      user-info-uri: ${authorization-server-uri}/userinfo
      token-info-uri: ${authorization-server-uri}/token/introspect
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk4rfDfGpqvTg83zE/lebD9qZfAeuSAKcKppfYIM64BeGDSuN3v8rmYL6Fu/t6Pw5se00IEUv9T/s+8r3hIYoXsbmdlDiLBu+Cob27/NVUZWE9ZGdmqhYE1KGsmeYzCJ8VIu9OOO1rygyiYuzh4wYcuISH1RRYHZYcZLMUnPqHgI09pTezr70BH5pKnWhiCxPgNgXZ3YIdq8H360v7Nso2drk8hXIjaMQ1543OztE7eSy0aSvX9hg9AJd6IRebdxaO1jsRCERntwcCs8/QCANsz41GkdXmRLFSx9J7SK5ku1zuVIUw3xBzXouUlvnbyOdNEB+bRk2KUIwQr2giLRBkQIDAQAB
          -----END PUBLIC KEY-----

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Server ###
server:
  port: 9010
  servlet:
    context-path: /api
