########################
# SPRING Configuration #
########################
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: oracle
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:billing;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
